[terminal.shell]
program = "/usr/bin/tmux"

[font]
size = 8.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[colors.primary]
background = '#000000'
foreground = '#c9d1d9'

[colors.normal]
black = '#484f58'
red = '#ff7b72'
green = '#3fb950'
yellow = '#d29922'
blue = '#58a6ff'
magenta = '#bc8cff'
cyan = '#39c5cf'
white = '#b1bac4'

[colors.bright]
black = '#6e7681'
red = '#ffa198'
green = '#56d364'
yellow = '#e3b341'
blue = '#79c0ff'
magenta = '#d2a8ff'
cyan = '#56d4dd'
white = '#f0f6fc'

[window]
opacity = 1.0
blur = false
decorations = "Full"
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors.cursor]
cursor = '#58a6ff'
text = '#0d1117'

[colors.selection]
background = '#3b5070'
text = '#c9d1d9'

[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001b[13;5u"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"